---
- name: Poll Jira for open bugs
  hosts: all
  sources:
    - redhat_iberia.eda.jira_jql:
        jira_url: "https://lboubeta.atlassian.net"
        jira_user: "lboubeta@redhat.com"
        jira_token: '{{ jira_api_token }}'
        jql: 'space = "ansible" AND status = "Waiting for support"'
        delay: 15

  rules:
    - name: Auto-assign highest priority bugs
      condition: event.fields.priority.name == "Highest"
      action:
        debug:
          msg: "Highest priority bug found: {{ event.fields.summary }}"
