---
version: 3

images:
  base_image:
    name: quay.io/ansible/ansible-rulebook:latest

dependencies:
  python: requirements.txt
  galaxy: requirements.yml

additional_build_steps:
  append_builder:
    - COPY . /tmp/jira.event_driven_ansible
    - RUN ansible-galaxy collection install /tmp/jira.event_driven_ansible
